version: 2
jobs:
  update-push-count:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Change ownership of file that needs to be updated
          command: chown -R $USER:$USER push_count.txt
      - run:
          name: Update the push_count.txt file.
          command: script/update_push_count
workflows:
  version: 2
  build:
    jobs:
    - update-push-count
